// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU9KIESV7G7ARWLNfmPrXKAgPxbPuIdd4',
    appId: '1:810919191177:web:2302d0676b185cd8029c58',
    messagingSenderId: '810919191177',
    projectId: 'kumbh-sarthi-23990',
    authDomain: 'kumbh-sarthi-23990.firebaseapp.com',
    storageBucket: 'kumbh-sarthi-23990.firebasestorage.app',
    measurementId: 'G-J8QGTD4XSE',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNOfSYMPQwqA_LUdFrtMxZGsMkvuNhRs4',
    appId: '1:810919191177:android:02f7853154c3e46b029c58',
    messagingSenderId: '810919191177',
    projectId: 'kumbh-sarthi-23990',
    storageBucket: 'kumbh-sarthi-23990.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwCMncwO-0hUkusswJHafZDn8blWTcw5g',
    appId: '1:810919191177:ios:8362a5b663991759029c58',
    messagingSenderId: '810919191177',
    projectId: 'kumbh-sarthi-23990',
    storageBucket: 'kumbh-sarthi-23990.firebasestorage.app',
    iosBundleId: 'com.example.kumbhSarthi',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwCMncwO-0hUkusswJHafZDn8blWTcw5g',
    appId: '1:810919191177:ios:8362a5b663991759029c58',
    messagingSenderId: '810919191177',
    projectId: 'kumbh-sarthi-23990',
    storageBucket: 'kumbh-sarthi-23990.firebasestorage.app',
    iosBundleId: 'com.example.kumbhSarthi',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU9KIESV7G7ARWLNfmPrXKAgPxbPuIdd4',
    appId: '1:810919191177:web:e6ab31cc64a15804029c58',
    messagingSenderId: '810919191177',
    projectId: 'kumbh-sarthi-23990',
    authDomain: 'kumbh-sarthi-23990.firebaseapp.com',
    storageBucket: 'kumbh-sarthi-23990.firebasestorage.app',
    measurementId: 'G-68YGQ5HNTY',
  );
}

